### PR TITLE
chore: added grids to responsive design in foundation

### PR DESCRIPTION
**Pull request by sarojgurung**
@danielwang i've added the grids in the responsive design section as it already has a grid topic in it. please let me know if it has to be under a different section

### CODE REVIEW

**Review by danielwang — COMMENTED** [review]
I think there is much better way of display the grids and responsiveness. check this out https://gel.westpacgroup.com.au/articles/the-grid

**Comment by danielwang** [comment]
please also add internal links to design token under guides

**Comment by sarojgurung** [comment]
@danielwang Hey daniel, I've updated the content and added internal links which should be visible in the first screen of either grid or template for each other.

**Review by danielwang — APPROVED** [review]
Nice work! Please merge.

**Pull request merged**
